#!/usr/bin/env bash
# bash script that pigns an Ip address passed as argument
# Accepts a string as an argument
# Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS}
# ...if not argument
# pings the IP 5 times

if [ "$1" ]
then
	ping -w 5 "$1"
else
	echo "5-is_the_host_on_the_network {IP_ADDRESS}"
fi
