#!/usr/bin/env bash
# bash script that pings an Ip address passed as argument
# Accepts a string as an argument
# Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS}
# ...if not argument
# pings the IP 5 times


if [ $# -ne 0 ]
then
	ping -c 5 "$1"
else
	echo "USAGE: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
