#!/usr/bin/env bash
# bash script that configure Ubuntu server
# With Localhost to 127.0.0.2
# and Facebook to 8.8.8.8

cp /etc/host ~/hosts.new
eco "127.0.0.2 localhost" > ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new  /etc/hosts
